### ISSUE TITLE
Requres "Fabric, any version"

### ISSUE THREAD

**Issue by nonetrix** [Flourick/FVT-fabric#61]
![スクリーンショット 2021-12-01 20-34-29](https://user-images.githubusercontent.com/45698918/144347103-b4f60c0e-1a63-4f30-8cd5-6799ababd11a.png)

```
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric, any version.
Unmet dependency listing:
	 - Mod 'Flour's Various Tweaks' (fvt) 1.8.0-mc1.18 requires any version of fabric, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:188)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric, any version.
Unmet dependency listing:
	 - Mod 'Flour's Various Tweaks' (fvt) 1.8.0-mc1.18 requires any version of fabric, which is missing!
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:183)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:48)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:222)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:186)
	... 3 more

```

I have no idea what it means, I have the newest version of Fabric installed as of writing 0.12.8

**Comment by nonetrix** [comment]
Fabric API was missing
